"""Lifecycle bridge for the official DeepSeek Harness Web UI.

The desktop client intentionally does not reimplement the Harness agent loop.
It starts the official ``dsh web`` distribution on loopback and embeds that
first-party UI in a Qt WebEngine surface.  The subprocess receives the same
DeepSeek endpoint and API key as Chat, while its persistent home is isolated
under this application's data directory.
"""

from __future__ import annotations

import os
import re
import signal
import shutil
import socket
import subprocess
from pathlib import Path

from PySide6.QtCore import QObject, QProcess, QProcessEnvironment, QTimer, Signal
from PySide6.QtNetwork import QTcpSocket

from . import HARNESS_BUNDLE_DIR
from .config import APP_DIR, DEFAULT_BASE_URL


# The version was inspected from the official repository and npm package on
# 2026-09-10.  Pinning the developer-preview version avoids silently pulling a
# breaking runtime into an existing desktop release; a future desktop release
# can update this constant after re-running the same upstream audit.
HARNESS_PACKAGE = "@deepseek-ai/dsh@0.1.5-rc.1"
HARNESS_DISPLAY_VERSION = "0.1.5-rc.1"
HARNESS_REPOSITORY_URL = "https://github.com/deepseek-ai/deepseek-harness"
HARNESS_DOCS_URL = "https://deepseek-harness.github.io/deepseek-harness/"
HARNESS_START_TIMEOUT_MS = 180_000


def find_npx() -> str | None:
    """Find npx, preferring the runtime bundled into a release .app."""

    bundled = HARNESS_BUNDLE_DIR / "node" / "bin" / "npx"
    if bundled.is_file() and os.access(bundled, os.X_OK):
        return str(bundled)

    located = shutil.which("npx")
    if located:
        return located
    for candidate in (
        "/opt/homebrew/bin/npx",
        "/usr/local/bin/npx",
        "/usr/bin/npx",
    ):
        if Path(candidate).is_file() and os.access(candidate, os.X_OK):
            return candidate
    return None


def find_node() -> str | None:
    """Find Node.js, preferring the release-local executable."""

    bundled = HARNESS_BUNDLE_DIR / "node" / "bin" / "node"
    candidates = [bundled]
    npx = find_npx()
    if npx:
        candidates.append(Path(npx).resolve().parent / "node")
    located = shutil.which("node")
    if located:
        candidates.append(Path(located))
    candidates.extend(
        Path(candidate)
        for candidate in (
            "/opt/homebrew/bin/node",
            "/usr/local/bin/node",
            "/usr/bin/node",
        )
    )
    for candidate in candidates:
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return str(candidate)
    return None


def find_bundled_harness_cli() -> str | None:
    """Return the first-party CLI entry when a release bundled it."""

    cli = HARNESS_BUNDLE_DIR / "node_modules" / "@deepseek-ai" / "dsh" / "lib" / "bin.js"
    return str(cli) if cli.is_file() else None


def bundled_harness_available() -> bool:
    return bool(find_node() and find_bundled_harness_cli())


def find_free_port() -> int:
    """Reserve an available loopback port for the child web server."""

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.bind(("127.0.0.1", 0))
        return int(probe.getsockname()[1])


def harness_home() -> Path:
    return APP_DIR / "harness"


def _yaml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def ensure_harness_defaults(home: Path, cfg: dict) -> Path:
    """Create the first-party adapter settings once, without overwriting edits."""

    home.mkdir(parents=True, exist_ok=True)
    settings = home / "settings.yaml"
    if settings.exists():
        return settings
    base_url = str(cfg.get("base_url") or DEFAULT_BASE_URL).strip().rstrip("/")
    settings.write_text(
        "# Generated by DeepSeek; edit in Harness settings if needed.\n"
        "# The API key is intentionally supplied through the process environment.\n"
        "llm-deepseek:\n"
        "  apiKeyEnv: DEEPSEEK_API_KEY\n"
        f"  baseURL: {_yaml_string(base_url)}\n"
        "  thinking: enabled\n"
        "  reasoningEffort: high\n"
        "  maxTokens: 256000\n"
        "  models:\n"
        "    - id: deepseek-flash\n"
        "      name: DeepSeek V4.1 Flash\n"
        "      contextWindow: 1000000\n"
        "      maxTokens: 256000\n"
        "      inputModalities: [text, image]\n"
        "      systemPromptUpdate: in-history\n",
        encoding="utf-8",
    )
    return settings


class HarnessRuntime(QObject):
    """Start, probe, and stop one local official Harness server."""

    ready = Signal(str)
    stateChanged = Signal(str)
    failed = Signal(str)
    stopped = Signal()

    def __init__(self, cfg: dict, parent=None) -> None:
        super().__init__(parent)
        self._cfg = dict(cfg)
        self._process: QProcess | None = None
        self._probe_socket: QTcpSocket | None = None
        self._probe_timer = QTimer(self)
        self._probe_timer.setSingleShot(True)
        self._probe_timer.timeout.connect(self._probe)
        self._deadline_timer = QTimer(self)
        self._deadline_timer.setSingleShot(True)
        self._deadline_timer.timeout.connect(self._startup_timed_out)
        self._stopping = False
        self._ready = False
        self._server_reachable = False
        self._port = 0
        self._url = ""
        self._log: list[str] = []

    @property
    def url(self) -> str:
        return self._url

    @property
    def is_running(self) -> bool:
        return bool(self._process and self._process.state() != QProcess.ProcessState.NotRunning)

    @property
    def log(self) -> str:
        return "".join(self._log)[-6000:]

    def update_config(self, cfg: dict) -> None:
        self._cfg = dict(cfg)

    def start(self, working_directory: Path | None = None) -> None:
        if self.is_running:
            if self._ready:
                self.ready.emit(self._url)
            return

        npx = find_npx()
        node = find_node()
        bundled_cli = find_bundled_harness_cli()
        if node is not None and bundled_cli is not None:
            program = node
            arguments = [str(bundled_cli)]
        elif npx is not None:
            program = npx
            arguments = ["--yes", "--prefer-offline", HARNESS_PACKAGE]
        else:
            self.failed.emit(
                "未找到可用的 Harness 运行环境。请重新安装完整应用，或安装 Node.js 22.19+ / 24+ 后重试。"
            )
            return

        home = harness_home()
        try:
            ensure_harness_defaults(home, self._cfg)
            (home / "npm-cache").mkdir(parents=True, exist_ok=True)
            (home / "browser-cache").mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            self.failed.emit(f"无法准备 Harness 本地目录：{exc}")
            return

        self._port = find_free_port()
        self._url = f"http://127.0.0.1:{self._port}"
        self._ready = False
        self._server_reachable = False
        self._stopping = False
        self._log.clear()

        process = QProcess(self)
        process.setProgram(program)
        process.setArguments(
            arguments
            + [
                "web",
                "--no-open",
                "--port",
                str(self._port),
            ]
        )
        environment = QProcessEnvironment.systemEnvironment()
        path_value = environment.value("PATH", "")
        npx_dir = str(Path(npx).resolve().parent)
        if npx_dir not in path_value.split(os.pathsep):
            path_value = npx_dir + os.pathsep + path_value
        environment.insert("PATH", path_value)
        environment.insert("DSH_HOME", str(home))
        environment.insert("npm_config_cache", str(home / "npm-cache"))
        environment.insert("npm_config_prefer_offline", "true")
        environment.insert("LANG", "zh_CN.UTF-8")
        environment.insert("LC_ALL", "zh_CN.UTF-8")
        api_key = str(self._cfg.get("api_key") or "").strip()
        if api_key:
            environment.insert("DEEPSEEK_API_KEY", api_key)
        else:
            # Do not let an unrelated shell credential silently select a
            # different account than the one configured in Chat.
            environment.remove("DEEPSEEK_API_KEY")
        base_url = str(self._cfg.get("base_url") or DEFAULT_BASE_URL).strip().rstrip("/")
        environment.insert("DEEPSEEK_BASE_URL", base_url)
        process.setProcessEnvironment(environment)
        directory = working_directory if working_directory and working_directory.is_dir() else Path.home()
        process.setWorkingDirectory(str(directory))
        process.setProcessChannelMode(QProcess.ProcessChannelMode.SeparateChannels)
        process.readyReadStandardOutput.connect(self._read_output)
        process.readyReadStandardError.connect(self._read_output)
        process.errorOccurred.connect(self._process_error)
        process.finished.connect(self._process_finished)
        self._process = process
        self.stateChanged.emit("正在启动官方 Harness…")
        process.start()
        self._deadline_timer.start(HARNESS_START_TIMEOUT_MS)
        QTimer.singleShot(250, self._probe)

    def stop(self) -> None:
        process = self._process
        self._stopping = True
        self._probe_timer.stop()
        self._deadline_timer.stop()
        if self._probe_socket is not None:
            self._probe_socket.abort()
            self._probe_socket.deleteLater()
            self._probe_socket = None
        if process is None:
            self._kill_port_owner()
            self.stopped.emit()
            return
        if process.state() == QProcess.ProcessState.NotRunning:
            self._process = None
            process.deleteLater()
            self._kill_port_owner()
            self.stopped.emit()
            return
        self.stateChanged.emit("正在关闭 Harness…")
        process.terminate()
        if not process.waitForFinished(5000):
            process.kill()
            process.waitForFinished(1500)
        self._kill_port_owner()

    def _kill_port_owner(self) -> None:
        """Clean up an npx child that detached after its wrapper exited."""

        if not self._port:
            return
        try:
            result = subprocess.run(
                ["lsof", "-ti", f"tcp:{self._port}"],
                capture_output=True,
                text=True,
                timeout=2,
                check=False,
            )
        except (OSError, subprocess.SubprocessError):
            return
        for value in result.stdout.splitlines():
            try:
                pid = int(value.strip())
            except ValueError:
                continue
            if pid == os.getpid():
                continue
            try:
                os.kill(pid, signal.SIGTERM)
            except ProcessLookupError:
                continue
            try:
                os.kill(pid, signal.SIGKILL)
            except ProcessLookupError:
                pass

    def _read_output(self) -> None:
        process = self._process
        if process is None:
            return
        for data in (
            bytes(process.readAllStandardOutput()),
            bytes(process.readAllStandardError()),
        ):
            if data:
                text = data.decode("utf-8", errors="replace")
                self._log.append(text)
                # The official Web runner protects the loopback UI with a
                # one-time query token.  Keep the printed URL (rather than
                # probing the bare port) so the embedded browser is
                # authenticated on its first navigation.
                match = re.search(
                    r"dsh web:\s+(https?://127\.0\.0\.1:\d+[^\s]*)",
                    self.log,
                )
                if match:
                    self._url = match.group(1).rstrip(".,")
        self._maybe_ready()

    def _probe(self) -> None:
        if self._stopping or self._ready or not self.is_running:
            return
        socket_probe = QTcpSocket(self)
        self._probe_socket = socket_probe
        socket_probe.connected.connect(self._server_connected)
        socket_probe.errorOccurred.connect(self._probe_failed)
        socket_probe.connectToHost("127.0.0.1", self._port)

    def _probe_failed(self, _error) -> None:
        socket_probe = self._probe_socket
        if socket_probe is not None:
            socket_probe.abort()
            socket_probe.deleteLater()
        self._probe_socket = None
        if not self._stopping and not self._ready:
            self._probe_timer.start(450)

    def _server_connected(self) -> None:
        if self._stopping or self._ready:
            return
        self._probe_timer.stop()
        socket_probe = self._probe_socket
        if socket_probe is not None:
            socket_probe.disconnectFromHost()
            socket_probe.deleteLater()
        self._probe_socket = None
        self._server_reachable = True
        self._maybe_ready()

    def _maybe_ready(self) -> None:
        if (
            self._stopping
            or self._ready
            or not self._server_reachable
            or "?token=" not in self._url
        ):
            return
        self._ready = True
        self._deadline_timer.stop()
        self.stateChanged.emit("Harness 已就绪")
        self.ready.emit(self._url)

    def _process_error(self, error) -> None:
        if self._stopping:
            return
        if error == QProcess.ProcessError.FailedToStart:
            self.failed.emit("无法启动 npx，请检查 Node.js 安装和 PATH。")

    def _process_finished(self, _exit_code: int, _status) -> None:
        self._read_output()
        process = self._process
        self._process = None
        self._probe_timer.stop()
        self._deadline_timer.stop()
        if process is not None:
            process.deleteLater()
        if self._stopping:
            self._kill_port_owner()
            self.stopped.emit()
        elif not self._ready:
            self.failed.emit(
                "Harness 进程提前退出。请检查 Node.js、网络连接或查看 Harness 日志后重试。"
            )
        else:
            self.failed.emit("Harness 服务已停止，请重新启动。")

    def _startup_timed_out(self) -> None:
        if self._ready or self._stopping:
            return
        self.failed.emit("Harness 启动超时。首次启动需要下载官方运行包，请稍后重试。")
        self.stop()


__all__ = [
    "HARNESS_DISPLAY_VERSION",
    "HARNESS_DOCS_URL",
    "HARNESS_PACKAGE",
    "HARNESS_REPOSITORY_URL",
    "HarnessRuntime",
    "bundled_harness_available",
    "ensure_harness_defaults",
    "find_bundled_harness_cli",
    "find_free_port",
    "find_node",
    "find_npx",
    "harness_home",
]
